name: dse-language-reading-predictors
channels:
  - conda-forge
dependencies:
  - python=3.14
  - arviz>=0.23.4,<1.0
  - graphviz
  - numba>=0.65.0
  - numpy>=2.4.3
  - numpyro>=0.20.1
  - nutpie>=0.16.8
  - pymc>=5.28.4,<6.0
  - pytorch>=2.10.0
  - pip
  - pip:
      - dcor
      - hatch
      - ipython>=9.12.0
      - jupytext
      - matplotlib>=3.10.8
      - networkx
      - notebook>=7.5.5
      - optuna>=4.8.0
      - pandas-stubs
      - pandas>=3.0.2
      - pandoc
      - psutil
      - pyarrow
      - pytest>=9.0.3
      - rich
      - ruff>=0.15.9
      - scikit-learn>=1.8.0
      - scipy-stubs
      - scipy>=1.17.1
      - seaborn>=0.13.2
      - setuptools>=81.0.0
      - lightgbm>=4.6.0
      - shap>=0.51.0
      - xgboost>=3.2.0
      - -e ../research/src/python #  for now, for local development
      - -e ./
