# Copyright (c) 2026 Down Syndrome Education International and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

"""Post-fit reporting helpers shared across the statistical models.

**A re-export facade since #637 stage 3.** The 9,417-line module this replaces was
one of the three dependency hubs the maintainability review named; it is now four
modules, split by what each answers:

* :mod:`estimands` - the quantities a fit reports: the average-marginal-effect
  cores, treatment and factor summaries, ROPE cards, DiD and joint contrasts, the
  association and concurrent marginals, the readiness knee, the horseshoe ranking.
* :mod:`predictive_checks` - the estimand-scale prior pushforwards (#381) and the
  posterior-predictive coverage statistics (#318).
* :mod:`run_metadata` - the fit's record of itself: run-plan resolution for the
  metadata writer, the fitted-row / model-design / environment identities, and the
  versioned trace-reuse contract.
* :mod:`key_findings` - the plain-language findings box (#320), one builder per
  family, plus the convergence-gate readers its verdict depends on.

The dependency edges between them run one way: ``predictive_checks`` uses three
average-marginal-effect cores from ``estimands``, and nothing else crosses.

Every name is re-exported here so the existing call sites and tests keep working.
That is **temporary**, exactly as #637 asks of the factory split: new code should
import from the owning module, and this facade should shrink as call sites move.
It is a compatibility seam, not an architecture.
"""

from __future__ import annotations

# Third-party helpers the pre-split module also re-exported. Several call sites
# import them from here rather than from ``dse_research_utils`` directly, so the
# facade keeps them until those call sites move too.
from dse_research_utils.statistics.evidence import (  # noqa: F401
    evidence_label,
    favoured_direction,
    odds_string,
)
from dse_research_utils.statistics.intervals import eti_bands  # noqa: F401
from dse_research_utils.statistics.rope import rope_card  # noqa: F401
from language_reading_predictors.statistical_models.convergence import (  # noqa: F401
    _KF_BFMI_MIN,
    _KF_CHECK_LABELS,
    _KF_ESS_MIN,
    _KF_REQUIRED_CHECKS,
    _KF_RHAT_MAX,
    _raw_convergence_gate_checks,
    convergence_gate_badge_markdown,
    convergence_gate_clean_passed,
    convergence_gate_failures,
)

from language_reading_predictors.statistical_models.estimands import (  # noqa: F401
    AssociationTerm,
    ConcurrentTerm,
    DEPENDENCE_INFORMED_RATIO,
    DEPENDENCE_PRIOR_DOMINATED_RATIO,
    REPORTING_CI_PROB,
    _KNEE_MIN_CURVATURE,
    _KNEE_MIN_INCREASING,
    _dependence_verdict,
    _factor_corr_draws,
    _itt_ame_draws,
    _joint_ame_draws,
    _joint_observed_row_masks,
    _readiness_knee,
    association_marginals,
    band50,
    beta_summary,
    block_exposure_summary,
    coef_row,
    concurrent_marginals,
    dependence_identification_summary,
    derived_mc_diagnostics,
    did_cell_ppc,
    did_summary,
    did_within_child_ppc,
    disattenuation_crosscheck,
    drop_retired_90_band,
    factor_summary,
    gamma_interaction_summary,
    growth_association_summary,
    horseshoe_ranking,
    joint_treatment_marginals,
    level_t2_marginal_effect,
    level_window_comparator_cards,
    longitudinal_conditional_slopes,
    longitudinal_factor_correlations,
    loo_delta,
    offfloor_mover_table,
    readiness_threshold,
    rope_markdown,
    rope_sensitivity,
    rope_sensitivity_markdown,
    rope_summary,
    tau_contrast_matrix,
    tau_difference_summary,
    tau_moderation_summary,
    tau_summary_itt,
    tau_summary_joint,
    tau_summary_offfloor,
    treatment_marginal_effect,
)

from language_reading_predictors.statistical_models.predictive_checks import (  # noqa: F401
    _indicator_prior_verdict,
    _offfloor_cell_rates,
    _ppc_node_arrays,
    indicator_prior_check,
    joint_prior_pushforward,
    labelled_pushforward,
    level_prior_pushforward,
    marginal_prior_pushforward,
    ppc_calibration_table,
    ppc_coverage_markdown,
    ppc_interval_coverage,
    ppc_interval_coverage_by_group,
    ppc_offfloor_cell_table,
    ppc_offfloor_rate_coverage,
    prior_pushforward,
    proportion_at_zero_ppc,
    pushforward_scale_for,
    pushforward_values,
    unavailable_pushforward,
)

from language_reading_predictors.statistical_models.run_metadata import (  # noqa: F401
    REUSE_CONTRACT_KEY,
    _FITTED_SUBJECT_IDENTITY_DOMAIN,
    _REUSE_CONFIG_FIELDS,
    _REUSE_CONTRACT_SCHEMA_VERSION,
    _adjusted_run_plan,
    _aligned_run_plan,
    _block_exposure_run_plan,
    _concurrent_run_plan,
    _corr_factor_run_plan,
    _did_run_plan,
    _dose_response_run_plan,
    _effective_model_settings,
    _fitted_data_identity,
    _gain_factors_run_plan,
    _growth_run_plan,
    _historical_growth_run_plan,
    _historical_joint_run_plan,
    _horseshoe_run_plan,
    _itt_analysis_set_metadata,
    _itt_run_plan,
    _joint_mechanism_run_plan,
    _joint_run_plan,
    _json_safe,
    _lcsm_run_plan,
    _level_factors_run_plan,
    _long_corr_factor_run_plan,
    _mechanism_run_plan,
    _mediation_run_plan,
    _model_design_identity,
    _pooled_levels_run_plan,
    _publication_input_contract,
    _resolved_run_plan,
    _reuse_compatibility_contract,
    _sha256_path,
    _survival_run_plan,
    fitted_subject_identity,
    require_reuse_compatibility,
    write_loo_summary,
    write_model_recipe,
    write_run_metadata,
)

from language_reading_predictors.statistical_models.key_findings import (  # noqa: F401
    KEY_FINDINGS_FILENAME,
    KEY_FINDINGS_MAX_SENTENCES,
    KEY_FINDINGS_SCHEMA_VERSION,
    _KF_BUILDERS,
    _KF_COVARIATE_MODERATOR_LABELS,
    _KF_DROPPABLE_ROLES,
    _KF_FACTOR_LABELS,
    _KF_MODERATION_LABELS,
    _KeyFindingsUnavailable,
    _PSENSE_CLEAR_MARKERS,
    _kf_association_direction,
    _kf_blending_link_evidence,
    _kf_build_adjusted,
    _kf_build_aligned,
    _kf_build_block_exposure,
    _kf_build_concurrent,
    _kf_build_corr_factor,
    _kf_build_did,
    _kf_build_dose_response,
    _kf_build_fallback,
    _kf_build_gain_factors,
    _kf_build_growth,
    _kf_build_historical_growth,
    _kf_build_historical_joint,
    _kf_build_horseshoe,
    _kf_build_itt,
    _kf_build_joint,
    _kf_build_joint_mechanism,
    _kf_build_lcsm,
    _kf_build_level_factors,
    _kf_build_long_corr_factor,
    _kf_build_mechanism,
    _kf_build_mediation,
    _kf_build_pooled_levels,
    _kf_build_survival,
    _kf_csv,
    _kf_csv_row,
    _kf_dag_unit,
    _kf_direction_words,
    _kf_float,
    _kf_growth_interaction_sentences,
    _kf_has_factor_term,
    _kf_headline_from_rope,
    _kf_itt_analysis_population,
    _kf_itt_attrition_bounds_clause,
    _kf_itt_causal_sentence,
    _kf_itt_missingness_sentence,
    _kf_jm_interval,
    _kf_jm_psense_flags,
    _kf_jm_wave_series,
    _kf_joint_marginal_phrase,
    _kf_joint_optional_text,
    _kf_joint_pp,
    _kf_level_blending_link_sentence,
    _kf_lower_first,
    _kf_measure_label,
    _kf_mechanism_curve_context,
    _kf_mechanism_shape_caveat,
    _kf_mechanism_slope_sentences,
    _kf_moderation_items_sentence,
    _kf_moderation_sentences,
    _kf_moderator_label,
    _kf_most_resolved_row,
    _kf_outcome_label,
    _kf_pair_selection_note,
    _kf_pct,
    _kf_plain_label,
    _kf_psense_diagnosis,
    _kf_rope_sentence,
    _kf_sentence,
    _kf_strongest_factor,
    _kf_with_release_note,
    _write_key_findings,
    generate_key_findings,
    mechanism_headline_estimand,
)

__all__ = [
    "AssociationTerm",
    "ConcurrentTerm",
    "DEPENDENCE_INFORMED_RATIO",
    "DEPENDENCE_PRIOR_DOMINATED_RATIO",
    "KEY_FINDINGS_FILENAME",
    "KEY_FINDINGS_MAX_SENTENCES",
    "KEY_FINDINGS_SCHEMA_VERSION",
    "REPORTING_CI_PROB",
    "REUSE_CONTRACT_KEY",
    "association_marginals",
    "band50",
    "beta_summary",
    "block_exposure_summary",
    "coef_row",
    "concurrent_marginals",
    "convergence_gate_badge_markdown",
    "convergence_gate_clean_passed",
    "convergence_gate_failures",
    "dependence_identification_summary",
    "derived_mc_diagnostics",
    "did_cell_ppc",
    "did_summary",
    "did_within_child_ppc",
    "disattenuation_crosscheck",
    "drop_retired_90_band",
    "factor_summary",
    "fitted_subject_identity",
    "gamma_interaction_summary",
    "generate_key_findings",
    "growth_association_summary",
    "horseshoe_ranking",
    "indicator_prior_check",
    "joint_prior_pushforward",
    "joint_treatment_marginals",
    "labelled_pushforward",
    "level_prior_pushforward",
    "level_t2_marginal_effect",
    "level_window_comparator_cards",
    "longitudinal_conditional_slopes",
    "longitudinal_factor_correlations",
    "loo_delta",
    "marginal_prior_pushforward",
    "mechanism_headline_estimand",
    "offfloor_mover_table",
    "ppc_calibration_table",
    "ppc_coverage_markdown",
    "ppc_interval_coverage",
    "ppc_interval_coverage_by_group",
    "ppc_offfloor_cell_table",
    "ppc_offfloor_rate_coverage",
    "prior_pushforward",
    "proportion_at_zero_ppc",
    "pushforward_scale_for",
    "pushforward_values",
    "readiness_threshold",
    "require_reuse_compatibility",
    "rope_markdown",
    "rope_sensitivity",
    "rope_sensitivity_markdown",
    "rope_summary",
    "tau_contrast_matrix",
    "tau_difference_summary",
    "tau_moderation_summary",
    "tau_summary_itt",
    "tau_summary_joint",
    "tau_summary_offfloor",
    "treatment_marginal_effect",
    "unavailable_pushforward",
    "write_loo_summary",
    "write_model_recipe",
    "write_run_metadata",
]
